### ISSUE TITLE
Display finishing date

### ISSUE THREAD

**Issue by lineaba** [lineaba/prog-o-meter#23]
Below the current line of text displayed in the prog-o-meter window stating how many days the user have left before they reach the goal, we should also display a line of text stating the end-date, i.e. the date on which they will reach their goal.

This requires that we calculate the end-date based on the current date + The number of remaining days of challenge (self.GOAL-self.days)

We should also make sure to update the the add_day method (belonging to the ProgressGUI class), so that when it is called, this line of text is updated. (Most likely the end-date will be the same, if the user is progressing at the "normal" speed. However, if they have not been progressing for one or more days, and then add a new day after their "hiatus", we should calculate, and display the new end-date)

Suggestion: You can add the new code to the canvas_layout method belonging to the ProgressGUI class. For inspiration on how to do it, check out the assignment of self.countdown_text in canvas_layout method belonging to ProgressGUI.
Maybe the python module datetime (https://docs.python.org/3/library/datetime.html) can be used to calculate which date it will be, x days from today.

**Comment by B-Souty** [comment]
Hey, I will take a look at this.

**Comment by lineaba** [comment]
Awesome, and welcome to the team. Let me know if you have any questions

**Comment by lineaba** [comment]
Hey @B-Souty how is it going with this issue? Let me know if you need any help or feedback :)

**Comment by B-Souty** [comment]
Hi lineaba,

I am submiting a PR right now.

**Comment by lineaba** [comment]
@B-Souty Awesome! I am so stoked that you did your first PR with the prog-o-meter, it was exactly for that reason I started the project. I will take a look at you PR within the next couple of hours 😃 Please let me know if you have any feedback on the github repo, if there is anything that could be explained better, organized differently, etc.

**Comment by B-Souty** [comment]
Feature added in #50

**Comment by B-Souty** [comment]
hmmm, I'm checking on my windows VM.

**Comment by B-Souty** [comment]
@lineaba Ok I found the issue on line 134: `return datetime.date.strftime(completion_date, "%B %-d{0}, %Y".format(suffix))`

Apparently "%-d" is not supported on windows instead we need to use "%d". On Linux it allows to display the day as 1st, 2nd, 3rd, 4th, ... instead of 01st, 02nd, 03rd, 04th, ...

the quick fix is to replace line 134 with  `return datetime.date.strftime(completion_date, "%B %d{0}, %Y".format(suffix))`

Shall I create a branch, fix it there and make a new PR or do you want to take care of it?

**Comment by lineaba** [comment]
Glad it was such a simple fix. I can change it and open a PR if you wanna approve it, or the other way around :)

**Comment by lineaba** [comment]
I have fixed it and opened a PR. Take a look, and see if you can approve when you have time :)

**Comment by B-Souty** [comment]
Alright, I'll approve it as soon as it's in. My apologies for that, I had no idea there was such difference betzeen windows and linux. I'll do my tests on my windows VM as well from now on.

**Comment by lineaba** [comment]
No worries, I hadn't either. I mainly use windows, so I hadn't considered these types of issues when I started collaborating. But it is all part of why I started the project, to be able to learn more of the "real issues"

**Comment by B-Souty** [comment]
@lineaba I edited your original comment on PR#60 to add a "#" in front of the issue number to create the link. This way, it gets automatically referenced in the issue ;)

**Comment by lineaba** [comment]
Cool, i probably missed it, thanks for adding it.
