### ISSUE TITLE
Print encouragements

### ISSUE THREAD

**Issue by lineaba** [lineaba/prog-o-meter#29]
We could implement a feature, where we print an encouragement to the user every day when they click the "1 more day button". Encouragements could be stuff like "Nice job!", or "Keep on learning", etc. or they could my motivational quotes, or something else nice. 
Encouragements could either be displayed as pop-up window, or just as a Tkinter text element above or below the prog-o-meter

Suggestion: Look at the current file, to see how text is displayed on a Tkinter canvas. To change encouragement each day, we can either have a set sequence (i.e. certain text to display on day one, two, three, etc.), or we can just have a collection of the texts/quotes we want to display, and randomly select one each time the "1 more day!" button is clicked

**Comment by kevalvc** [comment]
Hello, can i solve this issue?

**Comment by kevalvc** [comment]
@lineaba sure, thanks a ton.
