### ISSUE TITLE
Celebrate the reach of goal

### ISSUE THREAD

**Issue by lineaba** [lineaba/prog-o-meter#30]
Currently when the user reaches their goal, nothing happens (besides from the fact that the "1 more day!" button is disabled, to they can't add any more days)
This seems like a cause for celebration. Maybe we can display are celebratory message, gif, fireworks, or something else? Either as a pop-up window, or displayed directly on the canvas created in the ProgressGUI class. 
Lets get creative :)

**Comment by lineaba** [comment]
That's a nice idea, something to save and look back at.
If we do a web version at some point, there could also be interesting possibilities by having a twitter bot tweet out celebratory messages each time a user reaches a goal.

**Comment by brettvanderwerff** [comment]
Sounds good, something to keep on the back burner. I have never sent texts, but sending email with smtplib module is pretty straight forward, you would just need users to provide an email upon initial login. You also need a gmail account with access granted to less secure apps, which does not take much to set up. Some of the of the info in this link is deprecated, but its still very close: https://automatetheboringstuff.com/chapter16/

**Comment by lineaba** [comment]
I assume email is probably easier than text, since users could potentially be in many different countries with different carriers, etc, but have never looked into something like that (I did hear recently that google is coming out with a messaging solution similar to apple's iMessage sending over data, maybe the good old SMS is slowly going obsolete - well, this was a side note 😀 )
But we'll keep emails (and potentially texts) in mind, when we start working on goal celebration.

**Comment by garroadran** [comment]
Should be pretty easy to allow the user to share the event on their facebook timeline or twitter. I can get to work on that if you'd like.

**Comment by lineaba** [comment]
Yeah, that would be great!
