### ISSUE TITLE
Add a logging-feature

### ISSUE THREAD

**Issue by lineaba** [lineaba/prog-o-meter#32]
Writing a log is often considered an important part of the #100DaysofCode challenge. In a log the user would write some text everyday, about  their work that day. 
We could implement a feature (and maybe let the user decide themselves, whether to enable/disable it), which open a window with a text-input-field each day when they click the "1 more day!" button. The user can then write their log directly through the prog-o-meter program, and we could store it locally in a .txt file on their computer

Things to consider:
* Should it only be possible to add text to log when clicking the "1 more day!" button, or should a user who wanna update their log multiple times a day, have an opportunity to do that. 
* Should the user provide the headline (i.e. day 4), or should the program do that automatically.
* Make sure that we don't overwrite current text, when inputting new

**Comment by lineaba** [comment]
Here is a suggestion, if someone wanna have a try at this:
- Add a button to the prog-o-meter screen ("LOG")
- Check if the user currently have a file [USERNAME]_log.txt
    - If user do not have a log-file already, make one
- Open an entry widget (http://effbot.org/tkinterbook/entry.htm) (you can also take a look at the window that pops up for the user to enter their name in, for some inspiration on how to do this)
[USER TYPES THEIR LOG]
- Save the user's log input in their [USERNAME]_log.txt file (you can take a look at the update_days_file function in the current text, for inspiration on how to do this - just note that the update_days_file overwrites all existing text in the .txt file. For the log we would want in to just append the text in the end of the file)

Extra additions: Add a time stamp (i.e. get date and time of the input time, and put that in front of the input text in the file) - this doesn't have to be added straight away, we can always add it later

As always, the above is only a suggestion, and there a probably many other ways to solve the same problem, so feel very free to take your own approach

**Comment by sdkwok** [comment]
Hi, I'd like to take a look at this.

**Comment by lineaba** [comment]
That's awesome! I'll add you as a collaborator to the project. When you accept, please assign yourself to the issue (in the upper right corner of this window.) Let me know if you have any questions or would like some help getting started.

**Comment by sdkwok** [comment]
Hi, Linnea, I have been looking at the issue. I have two questions:

1) I'm not sure I have been added as collaborator on this project yet.

2) I'm thinking about having the [USERNAME]_log.txt file just be created in the main() routine along with the [USERNAME].txt file that records the number of days, so that any new user will automatically have an empty log file created for them.

Alternatively, we could make it so that the empty log file is created only when the user clicks the log button for the first time. What's your thoughts (or anyone's thoughts) on this?

**Comment by lineaba** [comment]
Hi, 
1. You are right, I had missed adding you. I have invited you now, you just need to accept my invitation, and then you should be able to self assign.
2. I think either of those solutions will work fine. I guess it is slightly unnecessary to have a log file, if the user never uses the logging-function. But we are also aiming for simplicity in our code, so if you think one of the solutions are easier, then I think we should choose that. Sorry that it isn't a clear-cut answer, let me know if you would like to brainstorm more about how to do it :)

**Comment by sdkwok** [comment]
Hi Linea,

I just made a pull request containing the new logging feature. A description of the changes is included with the request.
