### ISSUE TITLE
Change from progress-o-meter to prog-o-meter

### ISSUE THREAD

**Issue by lineaba** [lineaba/prog-o-meter#34]
When I first wrote the code, I used the name progress-o-meter, but later I decided to shorten it to prog-o-meter. It would be nice if we changed it in the code. 
This task requires NO programming skills, but you need to be able to use the github workflow (see the CONTRIBUTE file for guides, or ask for help in a comment on this issue). It could potentially be a nice way to look through and get familiarized with the code for this project, before committing to a larger task.
To change from "progress-o-meter", to "prog-o-meter", you can go through the code (if your editor have a find function, you can use that, to find all the places in the file, where it says "progress-o-meter", just like in word)
It would be awesome if we could change it both in code and comments (this just means EVERYWHERE in the prog-o-meter.py file)

**Comment by garroadran** [comment]
I'll have a go at this!

**Comment by lineaba** [comment]
Awesome! And welcome to the team

**Comment by lineaba** [comment]
This have been solved
