### ISSUE TITLE
Make user guide

### ISSUE THREAD

**Issue by lineaba** [lineaba/prog-o-meter#37]
We should make a user guide for how to use the prog-o-meter

**Comment by etiontdn** [comment]
Hi i'm new to opensource contributing and i want to help since it looks as simple as adding a tutorial of how to install and use i want to do it, if no one as done it already.

**Comment by lineaba** [comment]
Hey @etiontdn, welcome to the team! It would be super helpful if you would want to do that, and I think it would be a nice way to get introduced to the program, if you would be interested I'm making other contributions later. Let me know if you have any questions or want any help getting started.

**Comment by etiontdn** [comment]
Thanks! I want to ask if i should do it in the README.md or make a new file like TUTORIAL.md?

**Comment by etiontdn** [comment]
Thanks i will start working on it!

**Comment by lineaba** [comment]
That's awesome :)

**Comment by lineaba** [comment]
Hey, I am sorry I am a little slow with responses right now, as I am having exams and a travel ahead of me, I'm trying my best to keep up. I'll take a look.

**Comment by etiontdn** [comment]
All right, Good luck for with the exams and tripl  :smile:
