### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by brettvanderwerff** [lineaba/prog-o-meter#45]
Nice idea you have here, but you may want to seriously consider supporting/moving to python 3, especially because this is a new project and you are early on in development.

**Comment by elheffe80** [comment]
I was thinking the same thing. I’d rather put effort into python 3 as it is where everything is heading.

**Comment by lineaba** [comment]
Hey, thanks for your suggestions. I had been thinking the same thing, have been switching a bit between Python 2 and 3 due to different course requirements. Did this is python 2, because it was what I have been working in most recently. We can definitely work on a move or double support

**Comment by lineaba** [comment]
Cool, seems like there is consensus about Python 3. Okay with me to make the move.
