### ISSUE TITLE
Unused variable on line 130

### ISSUE THREAD

**Issue by lineaba** [lineaba/prog-o-meter#52]
Elheffe80 pointed out an unused variable (i) in a for loop on line 130. I will fix this as soon as possible, and go through and make the same doesn't occur elsewhere in the code too.

**Comment by 0xJosh** [comment]
Hey @lineaba, has this already been taken care of? - if not, I'd happily love to help.

**Comment by lineaba** [comment]
Hey @0xJosh, no I haven't actually fixed it yet, so if you wanna have a go at it, that would be awesome. I did find the same issue in at least one more line when I was looking through the code, but I of course forgot to write down which line (and there has been a couple of merges recently, so the problem elheffe80 originally pointed out, may have moved a few lines up or down also). It would be great if you would look through and see if you find other of the same cases (I haven't been using other variables than "i" for it, so it should be easy to do a search for all the cases, and check if "i" is actually being used or not. Let me know if you have any question or want some help :)

**Comment by lineaba** [comment]
@0xJosh I have added you as a contributor. When you accept, please assign yourself to this issue in the upper right corner.
