### ISSUE TITLE
Improve text_entry behavior

### ISSUE THREAD

**Issue by B-Souty** [lineaba/prog-o-meter#58]
Currently, once you chose if you're a new user or an existing one, on the next screen you need to click in the text box to start typing. Then click on submit to go to the next screen.

1. We could easily use the focus_set() method to activate the text box automatically so you don't have to click on it anymore. This is a one-liner `self.text_entry.focus_set()` after line 258. 
2. I was also wondering if there is a way to make it possible to hit 'Enter' to go to the next screen? In addition to the Submit button.

**Comment by lineaba** [comment]
Setting focus is a great idea, I'm all for it.
As for hitting enter, I don't know if there is a standardized way of doing it in Tkinter. I know Tkinter let's you take and save keyboard input, but I have only used it for the entire keyboard, not for a specific button. I think there could be some "hacky" solution, where we could check every time a key is pressed, whether the input is equal to "\n". It would mean that we would have to do that check for every letter that the user types when the input their name, which doesn't seem like the best solution.
Your idea is great, so if you want to work on it, that would be very awesome. Let me know if you want to brainstorm on other possible ways to do it
