### ISSUE TITLE
Limit click pr. day

### ISSUE THREAD

**Issue by lineaba** [lineaba/prog-o-meter#61]
In order to avoid that the user accidentally clicks "1 more day" twice in the same day, and then have to manually reset their count correctly, we could add a limit - either a fully enforced limit, or we could have have a pop-up if the user clicks the button again the same day, that asks "You already clicked once today, are you sure you meant to click again?"
We could store a timestamp for the latest click, and compare the current time of the new click against it, to see if the new click happens on the same day?  
What do the rest of you think about this?

If we do move forward with this, we should probably not add it to the program until we have issue #24 implemented. But if someone is interested, they can still go ahead an work on it.

**Comment by lineaba** [comment]
I think the database would be very helpful for this issue. We would be able to store the timestamp information of the user's last login in the database.

**Comment by nathanhannig** [comment]
My concerns of limiting to one click is if a user needs to mark the days that they may have forgot to login but actually did complete.

You could maybe limit it based on how many days since the last login. An Are you sure message seems like a good idea as well. 

I disagree adding any limits to the database model . Sounds like logic that needs to exist on the button event.

**Comment by lineaba** [comment]
hey, sorry it has taken me this long to get back to you @nathanhannig. I agree, that since we have now (almost - just waiting for some final changes before merge) added functionality that lets user remove a day if they clicked the button on accident, or manually set days (within 0-100), the limit it self does not add must value to the program 
(The talk of database was never to add a limit to the database, but just to store (in the database), the time/date for last button click, but that is also out of the picture now)
