### ISSUE TITLE
Change size of radio buttons

### ISSUE THREAD

**Issue by lineaba** [lineaba/prog-o-meter#62]
__First timers only__
_This means that this issue have been determined a good place to start for someone who have not been contributing to open source before. Let us know how we can help you get started or if you have any questions. We would really love for you to join us_

We have two buttons in the first window the user opens. Right now they have different width, and that looks a little silly. It would be great if we could set them to have the same width. This can be done by adding the width parameter to each of the radio button objects. 

[Here](http://effbot.org/tkinterbook/radiobutton.htm#Tkinter.Radiobutton.config-method) is  documentation for Tkinter radiobuttons. Check out the config part, and look for width. 
I don't know what the ideal width would be, It will require some experimentation.
The two radiobuttons are declared in the input_buttons(self) function, which belongs to the StartGUI class.
If someone have ideas for better text for each button, that is even clearer to the user, this is also very welcome. 

Let us know if you would like to work on this issue, and have any questions or would like some help.

**Comment by krishane2018** [comment]
Can I try this?

**Comment by lineaba** [comment]
Hey @krishane2018 welcome to the team, I'll take a look at your pull request :)

**Comment by krishane2018** [comment]
Alright thanks!
