### ISSUE TITLE
Get latest humble bundle dev!

### ISSUE THREAD

**Issue by elheffe80** [lineaba/prog-o-meter#72]
This is not related to prog-o-meter directly, but is a great resource!!

https://www.humblebundle.com/software/python-dev-kit-bundle

Not affiliated, nor an affiliate link.  However, there is a LOT of great stuff in there, so spend the $20 and get everything.  Totally worth it for the training videos, software, and everything.

**Comment by lineaba** [comment]
Nice suggestion. @elheffe80 when the humble bundle sale is over, will you close the issue? :)

**Comment by etiontdn** [comment]
The humble bundle is over.
 i think this issue should be closed.

**Comment by elheffe80** [comment]
As stated- bundle completed. Closing issue. Hope people got value from it.
