### ISSUE TITLE
The latest commit does'nt work on python 2 anymore

### ISSUE THREAD

**Issue by etiontdn** [lineaba/prog-o-meter#77]
Is it supposed to not be python 2 compatible?
is prog-o-meter moving to only python 3?

I made some tweaks on my local code for it to work for both python 2 and python 3 but i want to make sure that it is supposed to be like this or maybe it is only me.

**Comment by lineaba** [comment]
Sorry, I was not aware of that, I apologize that I didn't test it sufficiently. I think the general consensus between contributors have been that we focus on python 3. I understand this sentiment, and personally would be fine with moving to python 3 exclusively. Unless there are opinions against this, I will make the proper changes in documentation and make it clear that the prog-o-meter is a python3 based project. 
Let me know if you have any opinion on the matter?

**Comment by etiontdn** [comment]
@lineaba Don't worry i just think you should change the README to make sure no one gets a problem trying to run it with python2
 
it wasn't hard to make it work just made a change to the imports it looks like this:
```
prog-o-meter.py:

import datetime
import os, sys
try:
    from congratulations.Congratulations import Congratulations
except ImportError:
    cwd = os.getcwd()
    sys.path.insert(0, cwd+'/congratulations')
    from Congratulations import Congratulations

try:
    import Tkinter as Tk        # Python < 3.0
except ImportError:
    import tkinter as Tk        # Python >= 3.0
```
```
and congratulations/Congratulations.py:

import webbrowser as webbrowser
try:
    from urllib.parse import quote
except ImportError:
    from urllib import pathname2url as quote
try:
    import Tkinter as Tk        # Python < 3.0
except ImportError:
    import tkinter as Tk        # Python >= 3.0


```

**Comment by lineaba** [comment]
Cool, I'll update the readme. Thanks for letting me know :)

**Comment by lineaba** [comment]
readme is updated
